project:
  type: website
page-layout: article


website:
  title: LING0700
  page-navigation: true
  navbar:
    background: light
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lecture Notes"
        file: lecturenotes/r/r-basics.qmd
      - text: "Labs"
        file: labs/1-getting-started-with-r-lab.qmd
      - text: "Syllabus"
        file: syllabus.qmd

  sidebar:
    - title: "Home"
      # contents: 
      #   - index.qmd
      #   - syllabus.qmd
      #   - rubric.qmd
  
    - title: "Lecture Notes"
      contents:
        - section: "R"
          contents:
            - lecturenotes/r/r-basics.qmd
            - lecturenotes/r/data-importing.qmd

    - title: "Labs"
      contents:
        - labs/1-getting-started-with-r-lab.qmd
        # navigation items
    

# website:
#   title: "datasci for lang & mind"
#   page-navigation: true
#   sidebar:
#     contents:
#       - section: "Unit 1: R"
#         contents:
#           - href: lecturenotes/hello-world.qmd
#           - href: lecturenotes/r-basics.qmd
#           - href: lecturenotes/data-importing.qmd
#           - href: lecturenotes/data-visualization.qmd
#       - text: "---"
#       - section: "Unit 2: Stats"
#         contents:
#           - href: lecturenotes/probability-distributions.qmd
#           - href: document5.qmd
#           - href: document6.qmd

          # navigation items
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Schedule
  #     - href: syllabus.qmd
  #       text: Syllabus
  #     - href: rubric.qmd
  #       text: Rubric

format:
  html: 
    theme: cosmo
    css: styles.css
    # fontsize: 0.9em
    toc: true
    grid:
      sidebar-width: 300px
    #   gutter-width: 4em
    df-print: kable



