project:
  type: website
  output-dir: docs
callout-appearance: simple
website:
  title: LING 0700 | PSYC 2314
  page-navigation: true
  page-footer: Made with [Quarto](https://quarto.org/) &copy; 2023 Katie Schuler
  navbar:
    background: light
    search: true
    left:
    - text: Home
      file: index.qmd
    - text: Syllabus
      file: syllabus.qmd
    - text: Lecture notes
      file: notes/hello-world.qmd
    - text: Labs
      file: labs/lab-01.qmd
    - text: Problem sets
      file: psets/problem-set-01.qmd
    # tools:
    #   - icon: github
    #     href: https://github.com/kschuler/datasci
  sidebar:
  - title: Lecture notes
    contents:
    - notes/hello-world.qmd
    - notes/r-basics.qmd
    - notes/data-importing.qmd
    - notes/data-visualization.qmd
    - notes/data-wrangling.qmd
    - text: '---'
  - title: Labs
    contents: 
      - labs/lab-01.qmd
  - title: Problem sets
    contents:
    - psets/problem-set-01.qmd
    - text: '---'
    - rubric.qmd
format:
  html:
    theme: cosmo
    css:
    - styles.css
    - include/webex.css
    toc: true
    number-sections: true
    number-depth: 2
    grid:
      sidebar-width: 300px
    df-print: default
    include-in-header: include/webex.js
