project:
  type: website
  output-dir: docs
callout-appearance: simple
website:
  title: LING 0700 | PSYC 2314
  page-navigation: true
  page-footer: Made with [Quarto](https://quarto.org/) &copy; 2023 Katie Schuler
  navbar:
    background: light
    search: true
    left:
    - text: Home
      file: index.qmd
    - text: Syllabus
      file: syllabus.qmd
    - text: Office Hours
      file: syllabus.qmd#office-hours
    - text: Lecture notes
      file: notes/hello-world.qmd
    - text: Labs
      file: labs/lab-04.qmd
    - text: Problem sets
      file: psets/problem-set-02.qmd
    - text: Quizzes
      file: quizzes/quiz-study-guide.qmd
    # tools:
    #   - icon: github
    #     href: https://github.com/kschuler/datasci
  sidebar:
  - title: Lecture notes
    contents:
    - notes/hello-world.qmd
    - notes/r-basics.qmd
    - notes/data-importing.qmd
    - notes/data-visualization.qmd
    - notes/data-wrangling.qmd
    - text: '---'
    - notes/sampling-distribution.qmd
    - notes/hypothesis-testing.qmd
    - notes/model-specification.qmd
    - notes/model-accuracy.qmd
  - title: Labs
    contents:
      - labs/lab-01.qmd
      - labs/lab-02.qmd
      - labs/lab-03.qmd
      - labs/lab-04.qmd
      - text: "Lab 5: Hypothesis testing (Colab notebook)"
        url: https://colab.research.google.com/drive/1UzCgib6XIurxKAiNjn7GetvS6VWCocRd?usp=sharing
      - labs/lab-051.qmd
      - text: "Lab 6: Model fitting (Colab notebook)"
        url: https://colab.research.google.com/drive/1KCZMSCCDXW8NMjVqXkzV5I5mbMdLEPdE?usp=sharing
      - labs/lab-07.qmd
      - text: "Lab 7: Classification (Colab notebook)"
        url: https://colab.research.google.com/drive/1VhCLfcai1jCOfEFlRYLKgSC7EP9Kcgxj?usp=sharing
  - title: Problem sets
    contents:
    - psets/problem-set-01.qmd
    - text: Problem set 1 solutions
      url: https://colab.research.google.com/drive/1SE3nfYFeY3hvWVjmn2fNYtzNCVaaTQLM?usp=sharing
    - psets/problem-set-02.qmd
    - text: Problem set 2 solutions
      url: https://colab.research.google.com/drive/1wat_tzmHySFaXJh5n3kbfXqQ4UIFPClq?usp=sharing
    - psets/problem-set-03.qmd
    - text: Problem set 3 solutions
      url: https://colab.research.google.com/drive/1ckf5lO6tWXXk5POWsPSs0dr7ohLtjYUq?usp=sharing
    - psets/problem-set-04.qmd
    - text: Problem set 4 solutions
      url: https://colab.research.google.com/drive/1qrJkTLrxa-b-hnI1V3S4JHfS2y2w-9p6?usp=sharing
    - psets/problem-set-05.qmd
    - psets/problem-set-06.qmd
    - text: '---'
    - rubric.qmd
  - title: Quizzes
    contents:
      - quizzes/quiz-study-guide.qmd
      - text: '---'
      - quizzes/quiz-01.qmd
      - quizzes/quiz-01-solutions.qmd
      - text: '---'
      - quizzes/quiz-02.qmd
      - quizzes/quiz-02-solutions.qmd
      - text: '---'
      - quizzes/quiz-03.qmd
      - quizzes/quiz-03-solutions.qmd
format:
  html:
    theme: cosmo
    fontsize: 1em
    linestretch: 1.35
    css:
    - styles.css
    - include/webex.css
    toc: true
    number-sections: true
    number-depth: 2
    grid:
      sidebar-width: 300px
    df-print: default
    include-in-header: include/webex.js

